# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
config.load_autoconfig()

# Bindings for normal mode
config.bind(',v', 'hint links spawn mpv {hint-url}')

# Search Engines

# Default Search engine (startpage)
c.url.default_page = 'https://startpage.com/do/search?language=english&cat=web&query={}'

# Other search engines
c.url.searchengines = {
    'DEFAULT' : 'https://startpage.com/do/search?language=english&cat=web&query={}', # Default search engine (startpage)
    'aw' : 'https://wiki.archlinux.org/?search={}', # Searches through arch wiki
    'yx' : 'https://yandex.com/?q={}', # Searches through yandex search engine
    'sx' : 'https://searx.me/?q={}' , # Searches through searx.me search engine
    'yt' : 'https://www.youtube.com/results?search_query={}', # Searches through Youtube
    'ad' : 'http://anidb.net/perl-bin/animedb.pl?show=animelist&do.search=Search&adb.search={}', # searches through animedatabase
    'np' : 'https://nyaa.pantsu.cat/search?c=_&q={}', # searches through nyaa.pantsu.cat

        }
# Settings
c.fonts.monospace = 'Inconsolata'

# Startpage
c.url.start_pages = '~/Documents/startpages/tilde/index.html'



