#!/bin/bash
#
#
# Author: rlingam
#
# Description: Installs dotfiles and its dependencies
#
# Requires: yaourt (script assumes you have yaourt installed beforehand)
#
# Usage: ./install (or sudo ./install if you have to)
#        (this install script only works on arch, 
#         however you can use this install script as reference to install it yourself 
#         via package manager or compile from souce)
#
#

# Install stow first, as its needed for the next step

# For method 2, or if you only want the add dependencies portion add # in front of each line from

#here

sudo pacman -S stow

# Clone dotfiles and install them accordingly

cd ~/

mkdir Dotfiles

cd Dotfiles

git clone https://github.com/rlingam/dotfiles.git

sudo stow -v -t ~/ dotfiles


# to here

# intalls remaining packages using yaourt
sudo yaourt -S xorg-xwininfo  xrectsel imagemagick neofetch python2-potr vim-plug 

# intalls packages using pacman
sudo pacman -S alsa-utils scrot redshift feh slop wmctrl xdotool mpv vim zsh-syntax-highlighting scrot qutebrowser ffmpeg feh awk maim xclip wget youtube-dl mpc w3m irssi terminus-font cmus dmenu

cd ~/suckless/

# git clones st, dwm, slock, slstatus
# Its recommended you compile and install following programs in the given order
git clone git://git.suckless.org/st

cd ~/suckless/st 

sudo make clean install

echo "finished installing st (1/4)"



git clone https://git.suckless.org/dwm

cd ~/suckless/dwm

sudo make clean install

echo "finished installing dwm (2/4)"



git clone https://git.suckless.org/slock
cd ~/suckless/slock

sudo make clean install

echo "finished installing slock (3/4)"



git clone https://git.suckless.org/slstatus

cd ~/suckless/slstatus 

sudo make clean install



echo "finished installing slstatus (4/4)"

echo "Installation Finished"
