#!/bin/bash
#
#
# Author: rlingam
#
# Description: Installs dotfiles then its dependencies
#
# Requires: yaourt (script assumes you have yaourt installed beforehand)
#
# Usage: ./install (or sudo ./install if you have to)
#        (this install script only works on arch, 
#         however you can use this install script as reference to install it yourself 
#         via package manager or compile from souce)
#
#

# Install stow first, as its needed for the next step

# For method 2, or if you only want the add dependencies portion add # in front of each line from

#here

sudo pacman -S stow

# Clone dotfiles and install them accordingly

cd ~/

mkdir Dotfiles

cd Dotfiles

git clone https://github.com/rlingam/dotfiles.git

sudo stow -v -t ~/ dotfiles


# to here

#intalls remaining packages using yaourt
sudo yaourt -S rxvt-unicode-patched i3-gaps i3blocks-gaps-git lemonbar-xft-git xorg-xwininfo imgur-screenshot-git xrectsel imagemagick bmpanel2 neofetch python2-potr betterlockscreen-git python-pywal-git vim-plug

#intalls packages using pacman
sudo pacman -S compton alsa-utils rofi scrot redshift feh slop wmctrl xdotool openbox mpv vim zsh-syntax-highlighting scrot thunar qutebrowser ffmpeg feh dunst awk maim xclip wget mpd ncmpcpp youtube-dl mpc w3m irssi



