#!/bin/sh
# Dylan's Lemonbar Clock

# Source colors
#source ~/dotfiles/scripts/colors/output/colors.sh

while :; do
    echo "       $(neofetch --stdout memory) %{c}$(date "+%a %d %b %l:%M %p")%{r}$(mpc current | cut -c 1-25)      %{r}"
	sleep 2s
done |


lemonbar -d -g "500x33+720+20" -f "anonymous pro minus:size=7" -B "#1d232e" -F "#cccac0"
